repos:
  - repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files"]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        require_serial: true

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.1.0
    hooks:
    - id: mypy
